cat << 'EOF' > nginx-edge.conf
events {}

http {
    server {
        listen 80;

        location / {
            # Стираем фальшивые заголовки пользователя, берем только его реальный IP
            proxy_set_header X-Forwarded-For $remote_addr;
            
            # Жестко прописываем имя следующего контейнера
            proxy_pass http://nginx2:80;
        }
    }
}
EOF
